build-docker-image:
  script: 
  - sudo docker login -u "$PORTUS_USERNAME" -p "$PORTUS_PASSWORD" portus.cs.int:5000
  - sudo docker build -t hyena-proto-test .
  - sudo docker push portus.cs.int:5000/test/hyena-proto-test"\
  only:
  - master
  tags:
  - docker
